package com.litingzhe.scanutils.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.litingzhe.scanutils.model.BarCodeData;

import com.litingzhe.scanutils.db.BarCodeDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig barCodeDataDaoConfig;

    private final BarCodeDataDao barCodeDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        barCodeDataDaoConfig = daoConfigMap.get(BarCodeDataDao.class).clone();
        barCodeDataDaoConfig.initIdentityScope(type);

        barCodeDataDao = new BarCodeDataDao(barCodeDataDaoConfig, this);

        registerDao(BarCodeData.class, barCodeDataDao);
    }
    
    public void clear() {
        barCodeDataDaoConfig.clearIdentityScope();
    }

    public BarCodeDataDao getBarCodeDataDao() {
        return barCodeDataDao;
    }

}
